import { MAX_ADDRESS_LENGTH, MAX_PHONE_LENGTH, MD_DESCRIPTION_LENGTH, MAX_FAX_LENGTH } from 'src/common/constants';
import { CLIENT_FIELD_LENGTHS } from 'src/modules/clients/config/client.config';

export const ORDER_FIELD_LENGTHS = {
  REF: 255,
  NOTE: MD_DESCRIPTION_LENGTH,
  DELIVERY_ADDRESS: MAX_ADDRESS_LENGTH,
  //client info
  CLIENT_FULL_NAME: CLIENT_FIELD_LENGTHS.FULL_NAME,
  CLIENT_PHONE: MAX_PHONE_LENGTH,
  CLIENT_MOBILE: MAX_PHONE_LENGTH,
  CLIENT_FAX: MAX_FAX_LENGTH,
} as const;
