import { MAX_ADDRESS_LENGTH, MAX_PHONE_LENGTH, MD_DESCRIPTION_LENGTH , FAX_LENGTH } from 'src/common/constants';

export const ORDER_FIELD_LENGTHS = {
  REF : 255,
  NOTE: MD_DESCRIPTION_LENGTH,
  DELIVERY_ADDRESS: MAX_ADDRESS_LENGTH,
  //client info
  //todo : use client config instead
  CLIENT_FIRST_NAME: 255,
  CLIENT_LAST_NAME: 255,
  CLIENT_PHONE: MAX_PHONE_LENGTH,
  CLIENT_MOBILE: MAX_PHONE_LENGTH,
  CLIENT_FAX: FAX_LENGTH,
} as const;
