import {
  MAX_FILE_PATH_LENGTH,
  MD_DESCRIPTION_LENGTH,
} from '../../../common/constants/database-constraints.constant';

export const PRODUCT_FIELD_LENGTHS = {
  CODE: 255,
  REF: 255,
  IMG_PATH: MAX_FILE_PATH_LENGTH,
  DESCRIPTION: MD_DESCRIPTION_LENGTH,
  NOTE: MD_DESCRIPTION_LENGTH,
  LABEL: 100,
  LABEL2: 100,
} as const;
//PRODUCT_ENTITY_CONSTRAINTS

